---
- name: Search artifact
  artifactory:
    path: "{{ artifactory.path }}*app"
  register: search

- debug:
    var: search
    verbosity: 1

- block:
  - name: Download and unarchive
    unarchive:
      src: "{{ artifactory.url }}/{{ search.artifact.full_path }}"
      dest: "{{ app.temp_dir }}"
      remote_src: yes

  when: search.artifact.found
  rescue:
    - debug: msg='Download artifact with "{{ artifactory.path }}" failed'
