---
- name: Search artifact
  artifactory:
    path: "{{ artifactory.path }}*app"
  register: search

- debug:
    var: search
    verbosity: 1

- block:
  - name: Remove old directories
    file: path={{ item.value }} state=absent
    with_dict: "{{ app }}"

  - name: Create new directories
    file: path={{ item.value }} state=directory
    with_dict: "{{ app }}"

  - name: Create directories for logs
    file: path={{ logs_dir }} state=directory

  when: search.artifact.found
  rescue:
    - debug: msg='Preparing for artifact with path "{{ artifactory.path }}" failed'
