---
- name: Check properties
  assert:
    that:
      - product_name is defined

- name: Check product config schema
  local_action: >
    command java -jar {{ role_path }}/files/json-schema-validator-2.2.6-lib.jar
    --syntax
    {{ playbook_dir}}/schemas/{{ product_name }}-schema.json
