---
- debug: 
    var: has_server_conf
    verbosity: 1

- name: "Configure has_server_conf as ini file" 
  ini_file:
    dest: "{{ has_server_conf }}"
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    backup: no
    no_extra_spaces: yes
    create: no
  with_dict: "{{ ps.has_server.conf }}"
  
