---
- name: Check properties
  assert:
    that:
      - product_name is defined

- block:

  - name: Generate temp directory name
    set_fact:
      tmp_path: "{{ ansible_temp_dir | default('/tmp') }}/ansible-{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}_{{ 999999|random }}"

  - name: Create temp directory
    file:
      path: "{{ tmp_path }}"
      state: directory

  - name: Generate product config
    #debug: msg="{{ ps|json_query('{'~product_name~':'~product_name~'}')|to_nice_json(indent=2) }}"
    copy:
      content: "{{ ps|json_query('{'~product_name~':'~product_name~'}')|to_nice_json(indent=2) }}"
      dest: "{{ tmp_path }}/{{ product_name }}.json"

  - name: Generate product config schema
    local_action: >
      command java -jar {{ role_path }}/files/schema-guru-0.6.2.jar
      schema --output
      {{ playbook_dir}}/schemas/{{ product_name }}-schema.json.generated
      {{ tmp_path }}/{{ product_name }}.json

  - name: Remove temp directory
    file:
      path: "{{ tmp_path }}"
      state: absent

  become: no
  delegate_to: localhost
