---
- debug:
    var: artifact_path
    verbosity: 1

- set_fact:
    artifact_basename: "{{ artifact_path | basename }}"

- debug:
    var: artifact_basename
    verbosity: 1

- name: Move artifact to deploy
  shell: mv {{ artifact_path }} {{ app.deploy_dir }}

- name: Find content of artifact and check its installed
  set_fact:
    artifact_content: "{{ artifacts_content | selectattr('match', 'invert_match', artifact_basename) | list | union([None]) | first }}"

- debug:
    var: artifact_content
    verbosity: 1

- name: Check artifact installed
  include: check-artifact-installed.yml
  static: false
  when: artifact_content
