---
- name: Check properties
  assert:
    that:
      - app.deploy_dir is defined
      - app.temp_dir is defined
      - artifacts_deploy_order is defined
      - artifacts_content is defined

- name: Remove old frontends
  file: path={{ item }} state=absent
  with_fileglob:
    - "{{ app.deploy_dir }}/*"

- debug:
    var: artifacts_deploy_order
    verbosity: 1

- name: Deploy artifacts in appropriate order
  include: deploy-artifacts-by-pattern.yml
  static: false
  with_items: "{{ artifacts_deploy_order }}"
  loop_control:
    loop_var: artifacts_pattern

- name: Collect artifacts in {{ app.temp_dir }} dir
  find:
    paths: "{{ app.temp_dir }}"
    patterns: "*"
    use_regex: false
  register: artifacts_not_deployed

- debug: msg="artifacts_not_deployed {{ artifacts_not_deployed.files | map( attribute='path' ) | list }}"

- name: Check all artifacts were deployed
  fail:
    msg: "Not all artifacts were deployed from {{ app.temp_dir }}: {{ artifacts_not_deployed.files | map( attribute='path' ) | list | join(', ') }}"
  when: artifacts_not_deployed.files|length > 0
