---
- debug:
    var: feature_to_wait
    verbosity: 1

- name:  Wait feature to start
  shell: "{{ app.app_dir }}/container/bin/client feature:list | grep {{ feature_to_wait }} | grep -v Started"
  register: grep_result
  ignore_errors: yes
  until: grep_result.stdout_lines|length == 0
  retries: "{{ feature_start_timeout // 3 }}"
  failed_when: (grep_result.rc != 0) and (grep_result.stdout_lines != [])
  delay: 3

- debug:
    var: grep_result
    verbosity: 1

- name: Check if feature become Installed
  fail:
    msg: Feature is not installed in {{ feature_start_timeout }} sec period
  when: grep_result.failed
