---
- debug:
    var: bundles_to_wait
    verbosity: 1

- name: Make command to query statuses of bundles services
  template:
    src: status-of-services.cmd.j2
    dest: "{{ app.temp_dir }}/status-of-services.cmd"

- stat:
    path: "{{ app.temp_dir }}/status-of-services.cmd"
  register: st

- block:
  - name: Echo status-of-services.cmd
    command: cat {{ app.temp_dir }}/status-of-services.cmd

  - name: Wait until up all services
    shell: '{{ app.app_dir }}/container/bin/client -f {{ app.temp_dir }}/status-of-services.cmd 2>/dev/null | grep -vF "Logging in as karaf"'
    register: status_result
    failed_when: status_result.stdout_lines | select('search', '(Error|\\| false)') | list | length > 0

  - debug:
      var: status_result
      verbosity: 1

  - name: Check if all services've became Active
    fail:
      msg: Services've not activated in {{ service_up_timeout }} sec period
    when: status_result | failed

  when: st.stat.size > 0

- name: Drop status-of-services.cmd
  file:
    path: "{{ app.temp_dir }}/status-of-services.cmd"
    state: absent
